allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@rljson/rljson@0.0.82 || 0.0.83 || 0.0.84 || 0.0.85'
  - '@rljson/edge@0.0.1 || 0.0.2 || 0.0.3'
  - '@rljson/db@0.0.56 || 0.1.0'
  - '@rljson/io@0.0.84'
