/*
 * @license
 * Copyright (c) 2025 Rljson
 *
 * Use of this source code is governed by terms that can be
 * found in the LICENSE file in the root of this package.
 */

// Copies the use case page of @rljson/edge into the chapter »Generate
// Rljson«. The page and its images live in edge, which renders them from a
// real run of the generator: edge is the single source of truth.
//
// The SVGs are inlined, so the theme switch of the site can switch their
// colors. The page src/content/docs/guides/generate/usecase.md is
// generated; do not edit it by hand.

import { existsSync, realpathSync } from 'fs';
import { mkdir, readdir, readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** The page the script writes */
export const targetPage = join(
  root,
  'src',
  'content',
  'docs',
  'guides',
  'generate',
  'usecase.md',
);

/**
 * Finds the doc folder of @rljson/edge: in the published package, in a
 * linked checkout, or next to this repo in a ticket workspace.
 * @returns {string | undefined} The folder, or undefined
 */
export const findEdgeDoc = () => {
  const pkg = join(root, 'node_modules', '@rljson', 'edge');
  const candidates = [join(pkg, 'dist', 'doc'), join(root, '..', 'edge', 'doc')];
  if (existsSync(join(pkg, 'src'))) {
    candidates.splice(1, 0, join(realpathSync(join(pkg, 'src')), '..', 'doc'));
  }
  return candidates.find((dir) => existsSync(join(dir, 'architecture.md')));
};

/**
 * Makes an SVG of edge follow the theme switch of the site and fit the page.
 * @param {string} svg - The SVG
 * @returns {string} The SVG to inline
 */
export const themeSvg = (svg) =>
  svg
    .replace(
      /@media \(prefers-color-scheme: dark\)\{(svg\.uc\{[^}]*\})\}/,
      ":root[data-theme='dark'] $1",
    )
    .replace(/ width="\d+" height="\d+"/, ' style="width:100%;height:auto"')
    .trim();

/**
 * Turns the use case page of edge into a page of the site.
 * @param {string} markdown - The page of edge
 * @param {(file: string) => Promise<string>} readImage - Reads an image of edge
 * @returns {Promise<string>} The page of the site
 */
export const toSitePage = async (markdown, readImage) => {
  const body = markdown
    .replace(/<!--[\s\S]*?-->\s*/g, '')
    .replace(/^# .*\n+/m, '');

  const description = body
    .split('\n\n')
    .find((p) => !p.startsWith('#') && !p.startsWith('![')).replace(/\s+/g, ' ').trim();

  const parts = [];
  let last = 0;
  for (const match of body.matchAll(/!\[[^\]]*\]\(img\/([^)]+\.svg)\)/g)) {
    parts.push(body.slice(last, match.index));
    const svg = themeSvg(await readImage(match[1]));
    parts.push(`<figure class="uc-figure">\n${svg}\n</figure>`);
    last = match.index + match[0].length;
  }
  parts.push(body.slice(last));

  return [
    '---',
    'title: Example Usecase',
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    '<!-- Generated by scripts/sync-usecase.js from @rljson/edge. Do not edit. -->',
    '',
    parts.join('').trim(),
    '',
  ].join('\n');
};

/** The folder the themed images go to; the chapters of »Generate Rljson« import them */
export const imageDir = join(root, 'src', 'assets', 'usecase');

/** Writes the page and the images, or keeps them when edge is not found */
export const syncUsecase = async () => {
  const doc = findEdgeDoc();
  if (!doc) {
    console.warn('sync-usecase: @rljson/edge has no doc, keeping the page.');
    return;
  }
  const markdown = await readFile(join(doc, 'architecture.md'), 'utf8');
  const page = await toSitePage(markdown, (file) =>
    readFile(join(doc, 'img', file), 'utf8'),
  );
  await writeFile(targetPage, page);

  await mkdir(imageDir, { recursive: true });
  const images = (await readdir(join(doc, 'img'))).filter((f) =>
    f.startsWith('usecase-'),
  );
  for (const file of images) {
    const svg = await readFile(join(doc, 'img', file), 'utf8');
    await writeFile(join(imageDir, file), `${themeSvg(svg)}\n`);
  }
  console.log(`sync-usecase: wrote the page from ${doc}`);
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await syncUsecase();
}
