// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/rljson_github_io_version.spec.ts.

/** The version of the `rljson.github.io` package. */
export const rljsonGithubIoVersion = '0.1.0';
